[package]
name = "rocket_diving"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/first_gateway/lib.rs"
name = "first_gateway"

[[bin]]
path = "src/first_gateway/main.rs"
name = "first_gateway"

[dependencies]
rocket = "0.5.0-rc.2"
