[package]
name = "first_gateway"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "first_gateway"

[[bin]]
path = "src/main.rs"
name = "first_gateway"

[dependencies]
rocket = {workspace = true}
